---
- name: Create a new EC2 key
  ec2_key:
    name: access-key
    region: "{{ aws_region }}"
  register: ec2_key_result
            
- name: Save private key
  copy:
    content: "{{ ec2_key_result.key.private_key }}"
    dest: "./aws.access.pem"
    mode: 0600
  when: ec2_key_result.changed
...
